name: Build and Analyze

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest  # Sử dụng môi trường Windows

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Bước 2: Cài đặt SonarQube Scanner và chạy phân tích
      - name: Run SonarQube scan
        uses: SonarSource/sonar-scanner-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}  # Token từ GitHub Secrets
          sonar-host-url: http://1234abcd.ngrok.io  # URL ngrok thay cho SonarQube local
          projectBaseDir: .  # Chỉ định thư mục gốc của dự án
