name: Build and Analyze

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest  # Sử dụng môi trường Windows

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Lấy toàn bộ lịch sử thay vì chỉ commit gần nhất

      # Bước 2: Cài đặt SonarQube Scanner và chạy phân tích
      - name: Set up SonarQube Scanner
        uses: sonarsource/sonar-scanner-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}  # Token từ GitHub Secrets
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}  # URL của SonarQube từ GitHub Secrets
          projectBaseDir: .  # Chỉ định thư mục gốc của dự án
