name: Build and Analyze

on:
  push:
    branches:
      - master
      - develop
    # Thêm các nhánh khác nếu bạn muốn phân tích khi có push vào các nhánh đó

jobs:
  sonarqube-check:
    runs-on: ubuntu-latest  # Sử dụng Ubuntu container cho môi trường ổn định

    steps:
      # Bước 1: Checkout mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2  # Lấy mã nguồn từ repository của bạn

      # Bước 2: Sử dụng Docker Image SonarQube Scanner chính thức để phân tích mã
      - name: Run SonarQube scan
        uses: sonarsource/sonar-scanner-cli@v2
        with:
          args: >
            -Dsonar.projectKey=sillyphineas_FashionShop_ce8976e9-7afc-4ef2-ba57-c03dd7795b40
            -Dsonar.sources=src
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}  # URL ngrok mà bạn đã cấu hình trong GitHub Secrets
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # Token của SonarQube
