name: Build and Analyze

on:
  push:
    branches:
      - master
      - develop
    # Add any other branches you want to trigger analysis on

jobs:
  sonarqube-check:
    runs-on: ubuntu-latest  # Sử dụng môi trường Ubuntu (Docker sẽ chạy trên Ubuntu)

    steps:
      # Bước 1: Checkout mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2  # Lấy mã nguồn từ repository của bạn

      # Bước 2: Sử dụng Docker để chạy SonarQube Scanner
      - name: Run SonarQube scan using Docker
        uses: docker://sonarsource/sonar-scanner-cli:latest
        with:
          entrypoint: "sonar-scanner"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token của SonarQube
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # URL của SonarQube

      # Bước 3: Đảm bảo kết quả phân tích được lưu lại và hiển thị
      - name: Show SonarQube results
        run: echo "SonarQube analysis complete"
