name: Build and Analyze

on:
  push:
    branches:
      - master
      - develop
    # Add any other branches you want to trigger analysis on

jobs:
  sonarqube-check:
    runs-on: windows-latest  # Sử dụng môi trường Windows

    steps:
      # Bước 1: Checkout mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2  # Lấy mã nguồn từ repository của bạn

      # Bước 2: Cập nhật đường dẫn đến SonarQube Scanner
      - name: Add SonarQube Scanner to PATH
        run: |
          # Thêm đường dẫn tới sonar-scanner vào PATH
          echo "C:\\Users\\HP\\Desktop\\sonar-scanner-6.2.1.4610-windows-x64\\bin" >> $env:GITHUB_PATH
          # Kiểm tra phiên bản sonar-scanner để xác nhận
          sonar-scanner --version  # Kiểm tra xem SonarQube Scanner có được nhận diện không

      # Bước 3: Run SonarQube scan
      - name: Run SonarQube scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=sillyphineas_FashionShop_ce8976e9-7afc-4ef2-ba57-c03dd7795b40 \
            -Dsonar.sources=src \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}  # URL ngrok mà bạn đã cấu hình trong GitHub Secrets
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # Token của SonarQube mà bạn đã thêm vào GitHub Secrets
